---
kind: pipeline
type: docker
name: testing

steps:
- name: build
  image: golang:1.17.8
  commands:
  - go test ./...
  - sh scripts/build.sh

---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build-push
  pull: always
  image: golang:1.17.8
  commands:
  - "go build -v -ldflags \"-X main.build=${DRONE_BUILD_NUMBER}\" -a -o release/linux/amd64/plugin"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

- name: build-tag
  pull: always
  image: golang:1.17.8
  commands:
  - "go build -v -ldflags \"-X main.version=${DRONE_TAG##v} -X main.build=${DRONE_BUILD_NUMBER}\" -a -o release/linux/amd64/plugin"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
    - tag

- name: publish
  pull: always
  image: plugins/docker:linux-amd64
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: docker/Dockerfile.linux.amd64
    password:
      from_secret: docker_password
    repo: plugins/artifactory
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

- name: publish-ubi
  pull: always
  image: plugins/docker:linux-amd64
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64-ubi
    dockerfile: docker/Dockerfile.linux.ubi.amd64
    password:
      from_secret: docker_password
    repo: plugins/artifactory
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

trigger:
  ref:
  - refs/heads/main
  - "refs/tags/**"
  - "refs/pull/**"

depends_on:
- testing

---
kind: pipeline
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build-push
  pull: always
  image: golang:1.17.8
  commands:
  - "go build -v -ldflags \"-X main.build=${DRONE_BUILD_NUMBER}\" -a -o release/linux/arm64/plugin"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

- name: build-tag
  pull: always
  image: golang:1.17.8
  commands:
  - "go build -v -ldflags \"-X main.version=${DRONE_TAG##v} -X main.build=${DRONE_BUILD_NUMBER}\" -a -o release/linux/arm64/plugin"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
    - tag

- name: publish
  pull: always
  image: plugins/docker:linux-arm64
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm64
    dockerfile: docker/Dockerfile.linux.arm64
    password:
      from_secret: docker_password
    repo: plugins/artifactory
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

trigger:
  ref:
  - refs/heads/main
  - "refs/tags/**"
  - "refs/pull/**"

depends_on:
- testing

---
kind: pipeline
type: ssh
name: windows-1809-amd64

platform:
  os: windows

server:
  host: windows.1809.amd64.plugins.drone.ci
  password:
    from_secret: windows_password
  user:
    from_secret: windows_username

steps:
- name: build_latest
  environment:
    VERSION: 1809
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
  - powershell.exe scripts/windows/latest.ps1
  when:
    event: [ push ]

- name: build_nano_latest
  environment:
    VERSION: 1809
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
  - powershell.exe scripts/windows/latest_nano.ps1
  when:
    event: [ push ]

- name: build_tag
  environment:
    VERSION: 1809
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
  - powershell.exe scripts/windows/tag.ps1
  when:
    event: [ tag ]

depends_on:
  - testing

trigger:
  ref:
  - refs/heads/main
  - refs/tags/**

---
kind: pipeline
type: ssh
name: windows-1909-amd64

platform:
  os: windows

server:
  host: windows.1909.amd64.plugins.drone.ci
  password:
    from_secret: windows_password
  user:
    from_secret: windows_username

steps:
- name: build_latest
  environment:
    VERSION: 1909
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
  - powershell.exe scripts/windows/latest.ps1
  when:
    event: [ push ]

- name: build_tag
  environment:
    VERSION: 1909
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
  - powershell.exe scripts/windows/tag.ps1
  when:
    event: [ tag ]

depends_on:
  - testing

trigger:
  ref:
  - refs/heads/main
  - refs/tags/**

---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  pull: always
  image: plugins/manifest
  settings:
    ignore_missing: "true"
    auto_tag: "true"
    password:
      from_secret: docker_password
    spec: docker/manifest.tmpl
    username:
      from_secret: docker_username

trigger:
  ref:
  - refs/heads/main
  - "refs/tags/**"

depends_on:
- linux-amd64
- linux-arm64
- windows-1809-amd64
- windows-1909-amd64
...
