deps:
  apt:
    - jfrog-cli-v2-jf
  brew:
    - jfrog-cli
  choco:
    - jfrog-cli
run:
  binary:
    source: https://github.com/harness/drone-artifactory/releases/download/{{ release }}/plugin-{{ os }}-{{ arch }}.zst